# Generated by Django 5.2.4 on 2025-07-21 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 7, 21, 21, 5, 32, 694268, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
