# Generated by Django 5.2.4 on 2025-07-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodieApp', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
